# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement

# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
component: translator/prometheusremotewrite

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Add metric name to error message when invalid

# One or more tracking issues related to the change
issues: [18292]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: |
  Exporter prometheusremotewrite doesn't support non-cumulative monotonic, histogram, and summary OTLP metrics.
  Added metric name to error message when the unsupported metrics get dropped.
